### ISSUE TITLE
Code License?

### ISSUE THREAD

**Issue by dbeiler** [UweKeim/ZetaResourceEditor#16]
There haven't been many updates to this tool recently, and its dependence on the proprietary and paid DevExpress toolkit is an impediment to community development.

How is this code licensed?  How much of it can I reuse in a new (open source) project?

**Comment by UweKeim** [comment]
You can use _my_ code for whatever you want, no strings attached, no attribution required. 

(Although I love to get more backlinks to one of our applications: [a CMS](http://www.zeta-producer.com), [a Test Management Tool](http://www.zeta-test.com) or [a large file sending tool](https://www.zeta-uploader.com), if you want to do me favour).
