### ISSUE TITLE
Issue translating a large file from EN-GB to PT-BR or PT-PT with google translate

### ISSUE THREAD

**Issue by GuntherGUIDO** [UweKeim/ZetaResourceEditor#41]
Hi,

I've been using the tool for a few weeks now. 

But when I translate a file to Portugese (pt-br or pt-pt), the resulting file's content is in Tagalog (Philipines).

Kind regards,
Gunther

**Comment by UweKeim** [comment]
Could you give some more details? Like e.g.:

- a [MVCE](https://stackoverflow.com/help/minimal-reproducible-example) if possible
- which translator you are using (Google or Bing)

**Comment by GuntherGUIDO** [comment]
Hi Uwe, 

Thanks for looking into it.

I'm using the Google Translate functionality.
I have a paid subscription because of the large files we translate.

Our files our +/- 1.200 records long, but I seem te be getting the same result when translating a file of about 20 records long.

Hereby an image showing the result.

![image](https://user-images.githubusercontent.com/6337595/130410686-51e148af-d6c8-4583-b4f8-095d7bc08921.png)

**Comment by UweKeim** [comment]
As of now I've not managed to reproduce the issue. A MVCE would be really helpful.

**Comment by GuntherGUIDO** [comment]
Hi Uwe,

I cannot add RESX files to attachment, so I changed the extension to txt. [1199b.en-gb.txt](https://github.com/UweKeim/ZetaResourceEditor/files/7030220/1199b.en-gb.txt)

And I'm just using the standard Zeta Resource Editor version [2.3.0.30.]

Steps I take:

1. Add existing file to project (and choose the english RESX file)
2. Create new file for language (File group and reference language are autodetected, and I select the new language, in this case: Portugees (Brazilië). I check the upper 2 checkboxes. In Settings: "Google Translate is selected and correct JSON is there)
3. Depending on the size of the file, I wait from a few moments to about 20 minutes :)
4. Then I click "Edit resource files" and the new language appears in the grid.

With kind regards
Gunther

**Comment by UweKeim** [comment]
Found and fixed the issue. Thanks a lot! ♥ 

New setup (v2.3.0.31) should be available within the next few minutes.

**Comment by GuntherGUIDO** [comment]
Nono, thank you!!!

**Comment by GuntherGUIDO** [comment]
Just validated our big file, and works like a charm.
Wonderfull work Uwe!
