### ISSUE TITLE
App fails to open due to SecurityException

### ISSUE THREAD

**Issue by BrunoJuchli** [UweKeim/ZetaResourceEditor#49]
I've downloaded the portable version 2.3.0.33.
When starting ZetaResourceEditor.exe it seems like nothing is happening.

I'm running Windows 11 21H2 22000.65. .Net Framework 4.8 is installed.

The Windows event log contains two entries:

    <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
      <System>
        <Provider Name=".NET Runtime" /> 
        <EventID Qualifiers="0">1026</EventID> 
        <Version>0</Version> 
        <Level>2</Level> 
        <Task>0</Task> 
        <Opcode>0</Opcode> 
        <Keywords>0x80000000000000</Keywords> 
        <TimeCreated SystemTime="2022-05-05T12:57:18.7622202Z" /> 
        <EventRecordID>101777</EventRecordID> 
        <Execution ProcessID="31908" ThreadID="0" /> 
        <Channel>Application</Channel> 
      </System>
      <EventData>
        <Data>Application: ZetaResourceEditor.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.Security.SecurityException at ZetaResourceEditor.Code.Host.Main()</Data> 
      </EventData>
     </Event>

and 

    <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
      <System>
        <Provider Name="Application Error" /> 
        <EventID Qualifiers="0">1000</EventID> 
        <Version>0</Version> 
        <Level>2</Level> 
        <Task>100</Task> 
        <Opcode>0</Opcode> 
        <Keywords>0x80000000000000</Keywords> 
        <TimeCreated SystemTime="2022-05-05T12:57:18.8195156Z" /> 
        <EventRecordID>101778</EventRecordID> 
        <Execution ProcessID="18444" ThreadID="0" /> 
        <Channel>Application</Channel> 
      </System>
      <EventData>
        <Data>ZetaResourceEditor.exe</Data> 
        <Data>2.3.0.33</Data> 
        <Data>61842d6d</Data> 
        <Data>KERNELBASE.dll</Data> 
        <Data>10.0.22000.652</Data> 
        <Data>d680f8f6</Data> 
        <Data>e0434352</Data> 
        <Data>000000000004474c</Data> 
        <Data>7ca4</Data> 
        <Data>01d8607fa6eefc32</Data> 
        <Data>C:\Users\bruno\Downloads\ZetaResourceEditor-Bin\ZetaResourceEditor.exe</Data> 
        <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data> 
        <Data>cac19946-394f-4c26-afbd-f16fd2c49bb7</Data> 
      </EventData>
    </Event>

Note: i removed some empty fields and the computername field.

After the portable version failed I used the installer to install and can now successfully execute the application.

**Comment by UweKeim** [comment]
I've now removed the download links. Thanks for reporting this.
