### ISSUE TITLE
Neutral Language Column Wrong After Update

### ISSUE THREAD

**Issue by jlandreth3** [UweKeim/ZetaResourceEditor#50]
Hello,
Thanks for providing a very useful tool!

I have a problem after upgrading to version 2.3.28.0.   After the update the first column which should show English text is showing Chinese text.  See attached image.

![Neutral Langage Column Problem](https://user-images.githubusercontent.com/2372570/175097578-fb9087ed-1472-4174-a494-1d995c9b829c.png)

Any ideas?

Thanks
John.

**Comment by jlandreth3** [comment]
Updated attachment with more details.

![Neutral Langage Column Problem](https://user-images.githubusercontent.com/2372570/175097923-917969f9-1645-47f9-bfcd-5b30155cb677.png)

**Comment by albmargu** [comment]
I have the same problem. In the en-us column the chinese symbols are shown.
To solve it temporarily, I remove all files and add only main file (.resx), en-us and es-es files.

I hope it helps

**Comment by UweKeim** [comment]
In my tests on a Germany Win 11 64-bit, I am currently _not_ able to reproduce the issue:

![image](https://user-images.githubusercontent.com/415439/175255456-f13ab78e-7e7a-40a5-98c7-a8231b861deb.png)

Am I required to have Chinese as a string resource?

**Comment by albmargu** [comment]
I use more than 10 languages

**Comment by Kynothan** [comment]
Hello Everyone,
I have the same problem than @jlandreth3 .
Maybe the problem come from the Chinese language? I really don't know. 

![Sans titre 1](https://user-images.githubusercontent.com/101208857/175262025-ae5a1484-6f36-49db-be81-c01c3bb51685.png)

We tried to add the language files one by one and the problem only appears when we add the Chinese.

Cordially,

**Comment by UweKeim** [comment]
Let me repeat my request to anyone experiencing the same behavior:

Please provide me with a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

I.e. send me/upload here a ZIP file with:

- A .zreproj file
- Some example .resx files

so that I can see the error here in my environment, too.

**Comment by Kynothan** [comment]
Here is a minimal example that works for me,
Don't hesitate to tell me if it's enough or if you need something else.

[ZetaBug.zip](https://github.com/UweKeim/ZetaResourceEditor/files/8966168/ZetaBug.zip)

Cordially,

**Comment by UweKeim** [comment]
That was very helpful, thanks a lot, @Kynothan.

I do think I found and fixed the issue. Could you please take a look at [the just released update](https://zeta.li/zre-download-setup) and check whether it works better for you?

**Comment by Kynothan** [comment]
I just tried your released update with my project in is state and everything is good. I also tried it with `zh-Hans` and everything is good too.
Thanks a lot :)

**Comment by jlandreth3** [comment]
I found another issue with the new release.  When I use auto translate the software is not translating the last column.   See attached zip with sample project.

***@***.***


***@***.***


Regards,
John

From: Landreth, John R VIRT
Sent: Thursday, June 23, 2022 10:16 AM
To: UweKeim/ZetaResourceEditor ***@***.***>
Subject: RE: [UweKeim/ZetaResourceEditor] Neutral Language Column Wrong After Update (Issue #50)

Fixed for me as well.   Thanks for the quick response!

**Comment by jlandreth3** [comment]
Fix worked perfectly!  Thanks again!

**Comment by jlandreth3** [comment]
Thanks for the quick response.

See attached zip with example files.

Regards,
John
