### ISSUE TITLE
Broken UI on high DPI screen in v2.3.50.0

### ISSUE THREAD

**Issue by Tennyleaz** [UweKeim/ZetaResourceEditor#59]
After update to latest (v2.3.50.0), the UI is broken like the following screenshot, on DPI > 100%:

<img width="948" alt="螢幕擷取畫面 2023-07-14 133634" src="https://github.com/UweKeim/ZetaResourceEditor/assets/7089271/391dba9f-af6d-455d-a04c-dd0fbc751c6b">

Only working ok when I set DPI to 100%.

**Comment by UweKeim** [comment]
Thanks for reporting! Ironically, I've made the latest changes solely to support High DPI screens.

On my daily development machine I do have a High DPI screen myself, setting to 150% scale.

While I do _not_ get the erroneous display as in your screenshot, I might suspect that the DevExpress UI components I'm using are doing some DirectX stuff in the background, thus generating the errors you see.

I'll try to see whether I can disable DirectX support altogether.

Another issue _might_ be the non-western characters like Chinese or Korean that I did not test with.

**Comment by Tennyleaz** [comment]
A very fast reply!
Might not related, but this is my current environment:

- Windows 10 22H2, x64
- Dual screens, primary is 1440p 150%, secondary is 1080p 100%
- Ryzen 7 5700G with Radeon Graphics, driver version 23.5.2

**Comment by UweKeim** [comment]
I've done a very quick fix, by simply _not_ calling this line of code anymore:

```
WindowsFormsSettings.ForceDirectXPaint();
```

([See DX documentation](https://docs.devexpress.com/WindowsForms/DevExpress.XtraEditors.WindowsFormsSettings.ForceDirectXPaint))

I've just published a [**new setup**](https://zeta.li/zre-download-setup) with this change. 

Could you please take a look and give it a try whether things improve/change/worsen by this?

**Comment by Tennyleaz** [comment]
Wow you fixed it! Thank you!
Just tested, cannot see any other obvious error.

Another question is that, font in ZRE is not very sharp on higher DPI. Is this a feature or design limitation?
![螢幕擷取畫面 (172)](https://github.com/UweKeim/ZetaResourceEditor/assets/7089271/88efc49b-cb33-4ec9-923f-3cb3b3202b6b)
(Zoom this screenshot to see the blurry text)

**Comment by UweKeim** [comment]
This is how it looks on my 150% display:

<img width="960" alt="image" src="https://github.com/UweKeim/ZetaResourceEditor/assets/415439/257b55b7-cf13-4127-91e2-55798acb4fe7">

It _seems_ to be somewhat sharper than in your screenshot.

Honestly, I have no idea why this behaves so differently.

--------

The application uses "Segoe UI" font.

On my Windows 11 system, I have these one installed:

<img width="440" alt="image" src="https://github.com/UweKeim/ZetaResourceEditor/assets/415439/ee239749-e882-447c-8663-cf39f3b35aa6">
 
<img width="452" alt="image" src="https://github.com/UweKeim/ZetaResourceEditor/assets/415439/24819486-00fa-4b79-9ac1-b17ad6586da9">

Maybe your system has fewer "versions" of Segoe UI installed thus picking another one than on my system?

Or maybe Windows 10 renders Zeta Resource Editor different than Windows 11?

**Comment by Tennyleaz** [comment]
Found out I checked "Override high DPI scaling behavior" box for ZetaResourceEditor.exe to "System (Enhanced)".
It was my fault 😅
