### ISSUE TITLE
Some text are cropped in the export to excel dialog.

### ISSUE THREAD

**Issue by Tennyleaz** [UweKeim/ZetaResourceEditor#60]
Version 2.3.73.0 (and maybe previous versions too?)

The radio buttons and checkbox are cropped as follow image:
![圖片](https://github.com/UweKeim/ZetaResourceEditor/assets/7089271/a1d203d5-54c2-4158-8853-82376d15322a)

Occurs when DPI is not 100%.

**Comment by UweKeim** [comment]
Just some follow-up questions regarding your setup:

- Do you have multiple monitors?
- If yes, do they all have the same font scale settings (like e.g. "150%)?

**Comment by Tennyleaz** [comment]
Yes I have 2 monitors: primary is 1440p 150%, secondary is 1080p 100%. Same as in issue #59.
If I drag this dialog to the 2nd monitor, these radio buttons and checkbox text will become normal.

**Comment by UweKeim** [comment]
Thanks. I've just published an update that should fix the issue in the Excel export wizard.

**Comment by Tennyleaz** [comment]
The update fixed it.
Thank you!.
