### ISSUE TITLE
Use existing translations not working

### ISSUE THREAD

**Issue by jlandreth3** [UweKeim/ZetaResourceEditor#61]
Hello,
Thank you for maintaining this tool!

I am using Zeta version 2.3.73.0.

With the last two versions I have downloaded the "Use existing translations, if available" feature is not working as it did in the past.  

When an available translation exists, it is applied correctly.
When an available translation does not exist, Zeta does not call the translation service as it did before. 
Instead, Zeta leaves the value blank and changes the background color to yellow.

![Zeta - Use Existing Bug](https://github.com/UweKeim/ZetaResourceEditor/assets/2372570/8c5e53a8-838c-4312-adac-ec42c268c69b)

Any ideas?

Thanks!
John

**Comment by UweKeim** [comment]
I'll take a look at this, thanks for reporting.

**Comment by UweKeim** [comment]
Could you please:

- Assemble me a small test project to reproduce the issue (you can attach it here or send it to me uwe.keim@gmail.com).
- Tell me whether you are using Google or Microsoft translator.

Would be very helpful to me to find and fix the issue.

**Comment by UweKeim** [comment]
Thanks for sending me the example project.

I've just tried it:

![image](https://github.com/UweKeim/ZetaResourceEditor/assets/415439/a9dcf338-4f5e-4ee2-b905-6ff9fbf8711c)

And I see the erroneous behaviour.

When removing that "Use existing translations, if available" check, to my surprise, it worked:

![image](https://github.com/UweKeim/ZetaResourceEditor/assets/415439/3c39c25f-e19c-4895-968d-3afeef9545ba)

I'll now try to find the cause and publish an update.

**Comment by UweKeim** [comment]
I've released another update that did fix in my tests.

Please take a look whether this works better for you, too.

**Comment by jlandreth3** [comment]
The release on the main website https://www.zeta-resource-editor.com/ is 2.3.73.0 which is the version I have installed.

Where can I download this new release?

Thanks

**Comment by UweKeim** [comment]
Sorry, I broke my publish script.

Please try again,either through the website or the in-app update.

**Comment by jlandreth3** [comment]
Worked perfectly.  Thanks for the quick response!
