### ISSUE TITLE
Multilanguage GUI

### ISSUE THREAD

**Issue by bovirus** [UweKeim/ZetaResourceEditor#62]
@UweKeim 

Thanks for very important project.

Could you pelase modify source code to enable multilanguage GUI adding .resx for different language?

Thanks.

**Comment by UweKeim** [comment]
Thanks, @bovirus. I actually removed German language support several versions ago, keeping it English only.

Having a multi-language UI also requires all the dialogs/forms to have their own RESX files and the need to manually adjust in the WinForms designer.

Unfortunately, this is too much effort for this project.

Therefore I plan to keep the UI in English only.

**Comment by bovirus** [comment]
@UweKeim

I'm afraid that you take this decision.
If you reconsider this decision I can help with Italian.
Thanks.
