### ISSUE TITLE
Windows Installer - Icon in Windows Program list is a generic icon

### ISSUE THREAD

**Issue by bovirus** [UweKeim/ZetaResourceEditor#63]
@UweKeim 

At the end of installtion checking in Wiundows program List can see that the icon relative to the program is a generic icon and not a dedicated icon.

![image](https://github.com/user-attachments/assets/41101723-a429-4d5d-8ea3-11b10e47e5f0)

This is due probably to an error in Installer script.

If you can provide instalelr script I can help you to fix thi issue.

Thanks.

**Comment by UweKeim** [comment]
Thanks. I've just published version 2.3.86 that now has an uninstall icon:

![image](https://github.com/user-attachments/assets/24d40ddd-5392-4664-94b1-f05aefc6f074)

Thanks for pointing this out.

**Comment by bovirus** [comment]
@UweKeim 

Thanks for the fix.
Is the vesrion that you posted a program fix?
Because seems not a standard installer.
Didn't ask anything, install and close.

**Comment by UweKeim** [comment]
I hardly can understand your English sentences.

What are you trying to tell me: Does the new setup have a bug?

**Comment by bovirus** [comment]
@UweKeim 

Sorry. You are right.

I forgot that your installeris ia lways in this way.,
No request about folder to install, etc.
Ruin installer and stop.

Then the new installer is right. Sorry.
